version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: agent-minder-mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongodb-test:
    image: mongo:6.0
    container_name: agent-minder-mongodb-test
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=testadmin
      - MONGO_INITDB_ROOT_PASSWORD=testpassword
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongodb_data:
